GET http://localhost:3000/users/



###
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "bunny",
  "name": "Varshik",
  "password": "richbunny",
  "gender": "male",
  "location": "Milwaukee"
}


###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "bunny",
  "password": "richhhbunny"
}


###

PUT  http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "bunny",
  "oldPassword": "richbunny",
  "newPassword": "new"
}